name: Deploy to AKS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set AKS context
      uses: azure/aks-set-context@v3
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        cluster-name: aks-shahin
        resource-group: rg-devops-shahin

    - name: Get secret from Key Vault
      id: getsecret
      uses: azure/get-keyvault-secrets@v1
      with:
        keyvault: aks-shahin-kv
        secrets: 'nginx-password'

    - name: Create K8s Secret
      run: |
        kubectl create secret generic nginx-secret \
          --from-literal=password=${{ steps.getsecret.outputs.nginx-password }} \
          --dry-run=client -o yaml | kubectl apply -f -

    - name: Deploy to AKS
      run: |
        kubectl apply -f k8s/
